name: paystack
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.19.0
  meta: ^1.8.0
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.12
  mockito: ^5.3.1


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/


